# Generated by Django 4.2.4 on 2023-08-21 07:01

import app1.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/', validators=[app1.models.validate_file_size])),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime.now)),
                ('master_id', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dcs_moduls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dcs_ScrapingRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websitelink', models.URLField(default='null')),
                ('priority_list', models.CharField(choices=[('least', 'Least'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('choose_website', models.CharField(choices=[('Product', 'Product'), ('Brand', 'Brand'), ('Catagory', 'Catagory')], default='Product', max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[app1.models.validate_file_size])),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime.now)),
                ('reported', models.CharField(max_length=250)),
                ('specific', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='saveScapeUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.URLField()),
                ('file', models.FileField(upload_to='uploads_Scrape/', validators=[app1.models.validate_file_size])),
                ('module', models.CharField(default='', max_length=100)),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime.now)),
                ('uploaded_by', models.CharField(max_length=250)),
                ('master_id', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Signup_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('pass1', models.CharField(max_length=50)),
                ('pass2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_list', models.URLField()),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Dcs_ActionsForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websites', models.CharField(default='null', max_length=200)),
                ('assign_to', models.CharField(default='null', max_length=100)),
                ('assign_time', models.DateTimeField(default=datetime.datetime.now)),
                ('provided_by', models.CharField(default='null', max_length=100)),
                ('status', models.CharField(choices=[('In progress', 'In progress'), ('Done', 'Done'), ('On Hold', 'On Hold')], max_length=20)),
                ('websitelink', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='app1.dcs_scrapingrequisition')),
            ],
        ),
    ]
